version: 2

sources:
  - name: raw
    schema: raw  # Explicitly specify ClickHouse database
    tables:
      - name: autompg___cars_layn     # Must match EXACTLY (3 underscores)

  - name: clean
    database: clean   # ClickHouse schema/database
    tables:
      - name: mpg_standardized_layn
  
